name: image_font_add_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - image/apple.jpg
  fonts:
    - family: KR-Morning
      fonts:
        - asset: font/KR-Morning-Must1/KR-Morning-Must!.ttf
          weight: 400
